[project]
name = "aiwolf-nlp-llm-judge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiwolf-nlp-common>=0.6.10",
    "pyyaml>=6.0.2",
]
