# AIWolf ゲーム評価基準設定ファイル

# 共通評価項目（全ゲーム形式で実施）
common_criteria:
  - name: "logical_consistency"
    description: "推理の論理的一貫性"
    scale:
      min: 1
      max: 5
      type: "integer"
    
  - name: "information_usage"
    description: "情報活用の適切性"
    scale:
      min: 0.0
      max: 10.0
      type: "float"
    
  - name: "communication_quality"
    description: "コミュニケーション品質"
    scale:
      min: 1
      max: 5
      type: "integer"
    
  - name: "strategic_thinking"
    description: "戦略的思考力"
    scale:
      min: 0.0
      max: 5.0
      type: "float"

# ゲーム形式固有の評価項目
game_specific_criteria:
  5_player:
    - name: "quick_decision"
      description: "限られた情報での迅速な判断"
      scale:
        min: 0.0
        max: 1.0
        type: "float"
    
    - name: "role_adaptation"
      description: "少人数戦での役職適応"
      scale:
        min: 1
        max: 3
        type: "integer"
  
  13_player:
    - name: "coalition_management"
      description: "陣営形成・管理能力"
      scale:
        min: 1
        max: 7
        type: "integer"
    
    - name: "complex_reasoning"
      description: "複雑な状況での推理"
      scale:
        min: 0.0
        max: 5.0
        type: "float"
    
    - name: "information_filtering"
      description: "大量情報の取捨選択"
      scale:
        min: 1
        max: 10
        type: "integer"