# AIWolf ゲーム評価基準設定ファイル

# 共通評価項目（全ゲーム形式で実施）
common_criteria:
  - name: "natural_expression"
    description: "発話表現は自然か"
    scale:
      type: "int"
      min: 1
      max: 5
    
  - name: "contextual_dialogue"
    description: "文脈を踏まえた対話は自然か"
    scale:
      type: "int"
      min: 1
      max: 5
    
  - name: "logical_consistency"
    description: "発話内容は一貫しており矛盾がないか"
    scale:
      type: "int"
      min: 1
      max: 5
    
  - name: "action_consistency"
    description: "ゲーム行動（投票、襲撃、占いなど）は対話内容を踏まえているか"
    scale:
      type: "int"
      min: 1
      max: 5
  
  - name: "character_consistency"
    description: "発話表現は豊かか。与えられたプロフィールと矛盾なく、エージェントごとに一貫して豊かなキャラクター性が出ているか"
    scale:
      type: "int"
      min: 1
      max: 5

# ゲーム形式固有の評価項目
game_specific_criteria:
  13_player:
    - name: "team_play"
      description: "チームプレイができているか"
      scale:
        type: "int"
        min: 1
        max: 5