# AIWolf LLM Judge 設定ファイル

path:
  env: config/.env
  evaluation_criteria: config/evaluation_criteria.yaml

# LLM設定
llm:
  prompt_yml: config/prompts.yaml
  model: "gpt-5"

# ゲーム形式設定
game:
  format: "main_match"  # main_match または self_match
  player_count: 5  # プレイヤー数（5, 13など）

# 処理設定
processing:
  input_dir: "data/input"    # 入力ディレクトリ
  output_dir: "data/output"  # 出力ディレクトリ
  file_pattern: "*.log"      # ファイルパターン
  encoding: "utf-8"          # ファイルエンコーディング
  max_workers: 4             # プロセス並列処理数（ファイル間並列処理）
  translation_workers: 8     # スレッド並列処理数（ファイル内翻訳並列処理）
  buffer_threshold: 8192