# AIWolf LLM Judge 設定ファイル

path:
  env: config/.env
  evaluation_criteria: config/evaluation_criteria.yaml

# LLM設定
llm:
  prompt_yml: config/prompts.yaml
  model: "gpt-4o-mini"

# ゲーム形式設定
game:
  format: "main_match"  # main_match または self_match
  player_count: 5  # プレイヤー数（5, 13など）

# 処理設定
processing:
  input_dir: "data/input"    # 入力ディレクトリ
  output_dir: "data/output"  # 出力ディレクトリ
  encoding: "utf-8"          # ファイルエンコーディング
  max_workers: 4             # プロセス並列処理数（ゲーム間並列処理）
  evaluation_workers: 8      # スレッド並列処理数（評価基準並列処理）
  max_retries: 5             # LLMバリデーション失敗時の最大再試行回数